const fs = require('fs');
let code = fs.readFileSync('src/App.tsx', 'utf8');
const target = `  isError?: boolean;
  isHighThinking?: boolean;
}`;
const replacement = `  isError?: boolean;
  isHighThinking?: boolean;
  generatedImageUrl?: string;
  generatedImagePrompt?: string;
}`;
code = code.replace(target, replacement);
fs.writeFileSync('src/App.tsx', code);
